{% set name = "py-machineid" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py-machineid-{{ version }}.tar.gz
  sha256: 00c38d8521d429a4539bdd92967234db28a1a2b4b263062b351ca002332e633f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - winregistry

test:
  imports:
    - machineid
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/keygen-sh/py-machineid
  summary: Get the unique machine ID of any host (without admin privileges)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sbtq
    - cedrictq
